spring.application.name=ReceivablesGuard

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/receivables_guard
spring.datasource.username=receivablesguard_app
spring.datasource.password=meerut@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always